int S1 = 22;
int S2 = 23;
int S3 = 24;
int S4 = 25;
int S5 = 26;

int S6 = 27;
int S7 = 28;
int S8 = 29;
int S9 = 30;
int S10 = 31;

int S11 = 32;
int S12 = 33;
int S13 = 34;
int S14 = 35;
int S15 = 36;

int S16 = 37;
int S17 = 38;
int S18 = 39;
int S19 = 40;
int S20 = 41;

int S21 = 42;
int S22 = 43;
int S23 = 44;
int S24 = 45;
int S25 = 46;

int L1 = 2;
int L2 = 3;
int L3 = 4;
int L4 = 5;
int L5 = 6;
void setup() {
  pinMode(S1,OUTPUT);
  pinMode(S2,OUTPUT);
  pinMode(S3,OUTPUT);
  pinMode(S4,OUTPUT);
  pinMode(S5,OUTPUT);
  pinMode(S6,OUTPUT);
  pinMode(S7,OUTPUT);
  pinMode(S8,OUTPUT);
  pinMode(S9,OUTPUT);
  pinMode(S10,OUTPUT);
  pinMode(S11,OUTPUT);
  pinMode(S12,OUTPUT);
  pinMode(S13,OUTPUT);
  pinMode(S14,OUTPUT);
  pinMode(S15,OUTPUT);
  pinMode(S16,OUTPUT);
  pinMode(S17,OUTPUT);
  pinMode(S18,OUTPUT);
  pinMode(S19,OUTPUT);
  pinMode(S20,OUTPUT);
  pinMode(S21,OUTPUT);
  pinMode(S22,OUTPUT);
  pinMode(S23,OUTPUT);
  pinMode(S24,OUTPUT);
  pinMode(S25,OUTPUT);
  pinMode(L1,OUTPUT);
  pinMode(L2,OUTPUT);
  pinMode(L3,OUTPUT);
  pinMode(L4,OUTPUT);
  pinMode(L5,OUTPUT);
  
}

void boxn(){
  digitalWrite(L3,HIGH);
  delay(100);
  digitalWrite(S13,HIGH);
  delay(250);
  LEDlow();
  delay(100);
  digitalWrite(L4,HIGH);
  digitalWrite(L3,HIGH);
  digitalWrite(L2,HIGH);
  delay(100);
  digitalWrite(S9,HIGH);
  digitalWrite(S8,HIGH);
  digitalWrite(S7,HIGH);
  digitalWrite(S12,HIGH);
  digitalWrite(S17,HIGH);
  digitalWrite(S18,HIGH);
  digitalWrite(S19,HIGH);
  digitalWrite(S14,HIGH);
  delay(200);
  LEDlow();
  delay(100);
  digitalWrite(L1,HIGH);
  digitalWrite(L4,HIGH);
  digitalWrite(L3,HIGH);
  digitalWrite(L2,HIGH);
  digitalWrite(L5,HIGH);
  delay(100);
  digitalWrite(S5,HIGH);
  digitalWrite(S4,HIGH);
  digitalWrite(S3,HIGH);
  digitalWrite(S2,HIGH);
  digitalWrite(S1,HIGH);
  digitalWrite(S6,HIGH);
  digitalWrite(S11,HIGH);
  digitalWrite(S16,HIGH);
  digitalWrite(S21,HIGH);
  digitalWrite(S22,HIGH);
  digitalWrite(S23,HIGH);
  digitalWrite(S24,HIGH);
  digitalWrite(S25,HIGH);
  digitalWrite(S20,HIGH);
  digitalWrite(S15,HIGH);
  digitalWrite(S10,HIGH);
  delay(100);
  LEDlow();
  delay(100);
  }
void boxb(){
  digitalWrite(L1,HIGH);
  digitalWrite(L4,HIGH);
  digitalWrite(L3,HIGH);
  digitalWrite(L2,HIGH);
  digitalWrite(L5,HIGH);
  delay(100);
  digitalWrite(S5,HIGH);
  digitalWrite(S4,HIGH);
  digitalWrite(S3,HIGH);
  digitalWrite(S2,HIGH);
  digitalWrite(S1,HIGH);
  digitalWrite(S6,HIGH);
  digitalWrite(S11,HIGH);
  digitalWrite(S16,HIGH);
  digitalWrite(S21,HIGH);
  digitalWrite(S22,HIGH);
  digitalWrite(S23,HIGH);
  digitalWrite(S24,HIGH);
  digitalWrite(S25,HIGH);
  digitalWrite(S20,HIGH);
  digitalWrite(S15,HIGH);
  digitalWrite(S10,HIGH);
  delay(100);
  LEDlow();
  delay(100);

  digitalWrite(L4,HIGH);
  digitalWrite(L3,HIGH);
  digitalWrite(L2,HIGH);
  delay(100);
  digitalWrite(S9,HIGH);
  digitalWrite(S8,HIGH);
  digitalWrite(S7,HIGH);
  digitalWrite(S12,HIGH);
  digitalWrite(S17,HIGH);
  digitalWrite(S18,HIGH);
  digitalWrite(S19,HIGH);
  digitalWrite(S14,HIGH);
  delay(200);
  LEDlow();
  delay(100);

  digitalWrite(L3,HIGH);
  delay(100);
  digitalWrite(S13,HIGH);
  delay(250);
  LEDlow();
  delay(250);
  }

void LEDlow(){
  digitalWrite(L1,LOW);
  digitalWrite(L2,LOW);
  digitalWrite(L3,LOW);
  digitalWrite(L4,LOW);
  digitalWrite(L5,LOW);
  digitalWrite(S1,LOW);
  digitalWrite(S2,LOW);
  digitalWrite(S3,LOW);
  digitalWrite(S4,LOW);
  digitalWrite(S5,LOW);
  digitalWrite(S6,LOW);
  digitalWrite(S7,LOW);
  digitalWrite(S8,LOW);
  digitalWrite(S9,LOW);
  digitalWrite(S10,LOW);
  digitalWrite(S11,LOW);
  digitalWrite(S12,LOW);
  digitalWrite(S13,LOW);
  digitalWrite(S14,LOW);
  digitalWrite(S15,LOW);
  digitalWrite(S16,LOW);
  digitalWrite(S17,LOW);
  digitalWrite(S18,LOW);
  digitalWrite(S19,LOW);
  digitalWrite(S20,LOW);
  digitalWrite(S21,LOW);
  digitalWrite(S22,LOW);
  digitalWrite(S23,LOW);
  digitalWrite(S24,LOW);
  digitalWrite(S25,LOW);

  }  
void LEDhigh(){
  digitalWrite(L1,HIGH);
  digitalWrite(L2,HIGH);
  digitalWrite(L3,HIGH);
  digitalWrite(L4,HIGH);
  digitalWrite(L5,HIGH);
  digitalWrite(S1,HIGH);
  digitalWrite(S2,HIGH);
  digitalWrite(S3,HIGH);
  digitalWrite(S4,HIGH);
  digitalWrite(S5,HIGH);
  digitalWrite(S6,HIGH);
  digitalWrite(S7,HIGH);
  digitalWrite(S8,HIGH);
  digitalWrite(S9,HIGH);
  digitalWrite(S10,HIGH);
  digitalWrite(S11,HIGH);
  digitalWrite(S12,HIGH);
  digitalWrite(S13,HIGH);
  digitalWrite(S14,HIGH);
  digitalWrite(S15,HIGH);
  digitalWrite(S16,HIGH);
  digitalWrite(S17,HIGH);
  digitalWrite(S18,HIGH);
  digitalWrite(S19,HIGH);
  digitalWrite(S20,HIGH);
  digitalWrite(S21,HIGH);
  digitalWrite(S22,HIGH);
  digitalWrite(S23,HIGH);
  digitalWrite(S24,HIGH);
  digitalWrite(S25,HIGH);
  }  

void loop() {
  digitalWrite(L1,HIGH);
  delay(250);
  digitalWrite(S10,HIGH);
  delay(250);
  digitalWrite(S9,HIGH);
  delay(250);
  digitalWrite(S8,HIGH);
  delay(250);
  digitalWrite(S7,HIGH);
  delay(250);
  digitalWrite(S6,HIGH);
  delay(250);
  digitalWrite(S11,HIGH);
  delay(250);
  digitalWrite(S16,HIGH);
  delay(250);
  LEDlow();
  delay(250);

  digitalWrite(L2,HIGH);
  delay(250);
  digitalWrite(S10,HIGH);
  delay(250);
  digitalWrite(S9,HIGH);
  delay(250);
  digitalWrite(S8,HIGH);
  delay(250);
  digitalWrite(S7,HIGH);
  delay(250);
  digitalWrite(S6,HIGH);
  delay(250);
  digitalWrite(S11,HIGH);
  delay(250);
  digitalWrite(S16,HIGH);
  delay(250);
  digitalWrite(S17,HIGH);
  delay(250);
  digitalWrite(S18,HIGH);
  delay(250);
  digitalWrite(S19,HIGH);
  delay(250);
  digitalWrite(S20,HIGH);
  delay(250);
  digitalWrite(S15,HIGH);
  delay(250);
  LEDlow();
  delay(250);

  digitalWrite(L3,HIGH);
  delay(250);
  digitalWrite(S10,HIGH);
  delay(250);
  digitalWrite(S9,HIGH);
  delay(250);
  digitalWrite(S8,HIGH);
  delay(250);
  digitalWrite(S7,HIGH);
  delay(250);
  digitalWrite(S11,HIGH);
  delay(250);
  digitalWrite(S17,HIGH);
  delay(250);
  digitalWrite(S18,HIGH);
  delay(250);
  digitalWrite(S19,HIGH);
  delay(250);
  digitalWrite(S20,HIGH);
  delay(250);
  LEDlow();
  delay(250);

  digitalWrite(L4,HIGH);
  delay(250);
  digitalWrite(S10,HIGH);
  delay(250);
  digitalWrite(S9,HIGH);
  delay(250);
  digitalWrite(S8,HIGH);
  delay(250);
  digitalWrite(S7,HIGH);
  delay(250);
  digitalWrite(S6,HIGH);
  delay(250);
  digitalWrite(S15,HIGH);
  digitalWrite(S13,HIGH);
  digitalWrite(S11,HIGH);
  delay(250);
  digitalWrite(S18,HIGH);
  digitalWrite(S20,HIGH);
  digitalWrite(S16,HIGH);
  delay(250);
  LEDlow();
  delay(250);

  digitalWrite(L5,HIGH);
  delay(250);
  digitalWrite(S14,HIGH);
  delay(250);
  digitalWrite(S10,HIGH);
  delay(250);
  digitalWrite(S4,HIGH);
  delay(250);
  digitalWrite(S3,HIGH);
  delay(250);
  digitalWrite(S7,HIGH);
  delay(250);
  digitalWrite(S11,HIGH);
  delay(250);
  digitalWrite(S17,HIGH);
  delay(250);
  digitalWrite(S23,HIGH);
  delay(250);
  digitalWrite(S24,HIGH);
  delay(250);
  digitalWrite(S20,HIGH);
  delay(250);
  digitalWrite(L4,HIGH);
  delay(250);
  digitalWrite(L3,HIGH);
  delay(250);
  digitalWrite(L2,HIGH);
  delay(250);
  digitalWrite(L1,HIGH);
  delay(250);
  LEDlow();
  delay(250);
  boxn();
  delay(100);
  boxb();
  delay(100);
  boxn();
  delay(100);
  boxb();
  delay(100);
  boxn();
  delay(100);
  boxb();
  delay(100);
  boxn();
  delay(100);
  boxb();
  delay(100);
}
